name: cake-crusher
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2022.07.19=haa95532_0
  - certifi=2022.9.14=py39haa95532_0
  - cython=0.29.32=py39hd77b12b_0
  - fftw=3.3.9=h2bbff1b_1
  - gensim=4.1.2=py39hd77b12b_0
  - icc_rt=2022.1.0=h6049295_2
  - intel-openmp=2021.4.0=haa95532_3556
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py39h2bbff1b_0
  - mkl_fft=1.3.1=py39h277e83a_0
  - mkl_random=1.2.2=py39hf11a4ad_0
  - numpy=1.21.5=py39h7a0a035_3
  - numpy-base=1.21.5=py39hca35cd5_3
  - openssl=1.1.1q=h2bbff1b_0
  - pip=22.1.2=py39haa95532_0
  - python=3.9.13=h6244533_1
  - scipy=1.7.3=py39h7a0a035_2
  - setuptools=63.4.1=py39haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - smart_open=5.2.1=py39haa95532_0
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sqlite=3.39.2=h2bbff1b_0
  - tzdata=2022c=h04d1e81_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.37.1=pyhd3eb1b0_0
  - wincertstore=0.2=py39haa95532_2
prefix: D:\Programs\Anaconda\envs\cake-crusher
